version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_database
      - redis_cache
    networks:
      - backend
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CACHE_HOST: ${CACHE_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3

  mysql_database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
    networks:
      - backend
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis_cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
   driver: bridge