version: '3'
services:

  backend-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_database
      - redis_cache
    networks:
      - backend
      - frontend
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3

  mysql_database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
    networks:
      - backend
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis_cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  frontend-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend-app:8000
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    depends_on:
      - backend-app

networks:
  frontend:
  backend:
   driver: bridge